// Code generated by cmd/gen; DO NOT EDIT.

package tools

var builtinToolsRaw = `[
  {
    "name": "static_query",
    "description": "Return full schema data for rendering the architecture graph and atom/edge details",
    "parameters": {
      "properties": {
        "env": {
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  {
    "name": "static_query_detail",
    "description": "Fetch content of a single leaf file",
    "parameters": {
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "id"
      ],
      "type": "object"
    }
  },
  {
    "name": "static_search",
    "description": "Search schema content (atom / edge / runtime / test / contract / interface path / table / topic)",
    "parameters": {
      "properties": {
        "q": {
          "type": "string"
        }
      },
      "required": [
        "q"
      ],
      "type": "object"
    }
  },
  {
    "name": "static_mutation",
    "description": "Atomic schema mutation; one object at a time (add/update/remove), backed by file changes, for AI orchestration and audit trail",
    "parameters": {
      "properties": {
        "atom": {
          "properties": {
            "description": {
              "type": "string"
            },
            "interfaces": {
              "properties": {
                "consumes": {
                  "items": {
                    "properties": {
                      "channel": {
                        "type": "string"
                      },
                      "contract": {
                        "type": "string"
                      },
                      "extend": {
                        "type": "object"
                      },
                      "id": {
                        "type": "string"
                      },
                      "protocol": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "protocol",
                      "id",
                      "channel"
                    ],
                    "type": "object"
                  },
                  "type": "array"
                },
                "provides": {
                  "items": {
                    "properties": {
                      "channel": {
                        "type": "string"
                      },
                      "contract": {
                        "type": "string"
                      },
                      "extend": {
                        "type": "object"
                      },
                      "id": {
                        "type": "string"
                      },
                      "protocol": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "channel",
                      "protocol"
                    ],
                    "type": "object"
                  },
                  "type": "array"
                }
              },
              "required": [
                "provides",
                "consumes"
              ],
              "type": "object"
            },
            "name": {
              "type": "string"
            },
            "path": {
              "type": "string"
            },
            "repo": {
              "type": "string"
            },
            "role": {
              "type": "string"
            },
            "runtime_type": {
              "type": "string"
            },
            "runtime_version": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "description",
            "runtime_type",
            "interfaces"
          ],
          "type": "object"
        },
        "contract": {
          "properties": {
            "description": {
              "type": "string"
            },
            "error": {
              "type": "object"
            },
            "id": {
              "type": "string"
            },
            "request": {
              "type": "object"
            },
            "response": {
              "type": "object"
            }
          },
          "required": [
            "id",
            "description",
            "request",
            "response",
            "error"
          ],
          "type": "object"
        },
        "devtime": {
          "type": "string"
        },
        "docs": {
          "type": "string"
        },
        "edge": {
          "properties": {
            "channel": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "from": {
              "type": "string"
            },
            "from_interface": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "protocol": {
              "type": "string"
            },
            "to": {
              "type": "string"
            },
            "to_interface": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "from",
            "from_interface",
            "to",
            "to_interface",
            "channel",
            "protocol",
            "description"
          ],
          "type": "object"
        },
        "id": {
          "type": "string"
        },
        "notes": {
          "type": "string"
        },
        "op": {
          "type": "string"
        },
        "runtime": {
          "properties": {
            "description": {
              "type": "string"
            },
            "endpoints": {
              "properties": {
                "\u003catom-id\u003e": {
                  "properties": {
                    "address": {
                      "type": "string"
                    },
                    "channel": {
                      "type": "string"
                    },
                    "in": {
                      "type": "string"
                    },
                    "out": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "channel"
                  ],
                  "type": "object"
                }
              },
              "required": [
                "\u003catom-id\u003e"
              ],
              "type": "object"
            },
            "telemetry": {
              "properties": {
                "\u003catom-id\u003e": {
                  "properties": {
                    "backend": {
                      "type": "string"
                    },
                    "endpoint": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "backend",
                    "endpoint"
                  ],
                  "type": "object"
                }
              },
              "required": [
                "\u003catom-id\u003e"
              ],
              "type": "object"
            },
            "tests": {
              "items": {
                "properties": {
                  "atoms": {
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  },
                  "case": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "edges": {
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  },
                  "id": {
                    "type": "string"
                  }
                },
                "required": [
                  "description",
                  "atoms",
                  "case",
                  "id"
                ],
                "type": "object"
              },
              "type": "array"
            }
          },
          "required": [
            "description",
            "endpoints"
          ],
          "type": "object"
        },
        "test": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "op",
        "type"
      ],
      "type": "object"
    }
  },
  {
    "name": "log_query",
    "description": "Query records (atom call / telemetry observe / ai conversation); list view",
    "parameters": {
      "properties": {
        "atom": {
          "type": "string"
        },
        "end": {
          "type": "string"
        },
        "env": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "pageNum": {
          "type": "number"
        },
        "sessionId": {
          "type": "string"
        },
        "start": {
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  {
    "name": "log_query_detail",
    "description": "Fetch a single record's full content",
    "parameters": {
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "type": "object"
    }
  },
  {
    "name": "log_search",
    "description": "Full-text search across records",
    "parameters": {
      "properties": {
        "pageNum": {
          "type": "number"
        },
        "q": {
          "type": "string"
        }
      },
      "required": [
        "q"
      ],
      "type": "object"
    }
  },
  {
    "name": "log_mutation",
    "description": "Write a record (ai only); op is add for now",
    "parameters": {
      "properties": {
        "atom": {
          "type": "string"
        },
        "env": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "op": {
          "type": "string"
        },
        "payload": {
          "type": "object"
        },
        "sessionId": {
          "type": "string"
        }
      },
      "required": [
        "payload",
        "op",
        "kind"
      ],
      "type": "object"
    }
  }
]`
